#!/usr/bin/env perl

use strict;
use warnings;
use File::Spec;
use File::Basename;
use lib File::Spec->catdir(dirname(__FILE__), 'extlib', 'lib', 'perl5');
use lib File::Spec->catdir(dirname(__FILE__), 'lib');

use Proclet::Declare;
use Iyemon::Config;

color;
env(
    LM_DEBUG => 1,
);

service('web' => 'plackup',
    '-r',
    '-a' =>  'app.psgi',
    '-R' => './config/common.pl',
    @{config->param('boostrap')->{web} || []},
);

run;
